#!/usr/bin/env python3
"""Render a redsalt-master minion pillar file for a Salt minion."""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

SUPPORTED_ROLES = ("base", "docker", "nvidia", "llm_vllm")


def parse_roles(value: str) -> list[str]:
    roles = [item.strip() for item in value.split(',') if item.strip()]
    unknown = sorted(set(roles) - set(SUPPORTED_ROLES))
    if unknown:
        raise argparse.ArgumentTypeError(f"unknown roles: {', '.join(unknown)}")
    if not roles:
        raise argparse.ArgumentTypeError("at least one role is required")
    if "base" not in roles:
        roles.insert(0, "base")
    return roles


def bool_text(value: bool) -> str:
    return "true" if value else "false"


def render(minion_id: str, roles: Iterable[str]) -> str:
    role_set = set(roles)
    lines: list[str] = [
        "# Generated by redsalt-minion/scripts/render-pillar.py",
        f"# Minion ID: {minion_id}",
        "roles:",
    ]
    for role in SUPPORTED_ROLES:
        lines.append(f"  {role}: {bool_text(role in role_set)}")

    if {"nvidia", "llm_vllm"} & role_set:
        lines.extend([
            "",
            "models:",
            "  path: /opt/models",
            "  owner: root",
            "  group: root",
            "  mode: '0755'",
            "",
            "nvidia:",
            "  driver:",
            "    install: false",
            "    package: nvidia-driver-550",
            "  container_toolkit:",
            "    package: nvidia-container-toolkit",
        ])

    if "llm_vllm" in role_set:
        lines.extend([
            "",
            "vllm:",
            "  image: vllm/vllm-openai:latest",
            "  service_name: vllm-openai",
            "  port: 8000",
            "  host: 0.0.0.0",
            "  model: /models/model",
            "  served_model_name: local-model",
            "  gpu_count: all",
            "  gpu_memory_utilization: 0.90",
            "  max_model_len: 32768",
            "  tensor_parallel_size: 1",
            "  enable_prefix_caching: true",
            "  trust_remote_code: false",
            "  extra_args: []",
            "  compose_dir: /opt/redsalt/vllm",
            "  env_file: /etc/redsalt/vllm.env",
            "  hf_cache: /var/cache/huggingface",
        ])

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--minion-id", required=True, help="Stable Salt minion ID")
    parser.add_argument("--roles", type=parse_roles, default=parse_roles("base"), help="Comma-separated roles")
    parser.add_argument("--output", help="Output file path. Defaults to stdout.")
    parser.add_argument("--print-top-entry", action="store_true", help="Also print pillar/top.sls entry to stderr")
    args = parser.parse_args()

    content = render(args.minion_id, args.roles)
    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)
    else:
        print(content, end="")

    if args.print_top_entry:
        import sys
        print("Add to redsalt-master/pillar/top.sls:", file=sys.stderr)
        print("base:", file=sys.stderr)
        print(f"  '{args.minion_id}':", file=sys.stderr)
        print(f"    - minions.{args.minion_id}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
